version: '3'

services:
  web:
    build:
      context: .
    container_name: structure_web
    environment:
      DATABASE_URL: $DATABASE_URL
    ports:
      - '8080:8080'
    # depends_on:
    #   - postgres

  # postgres:
  #   image: postgres:latest
  #   container_name: structure_postgres
  #   environment:
  #     POSTGRES_USER: $POSTGRES_USER
  #     POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  #     POSTGRES_DB: structure
  #   ports:
  #     - '5432:5432'
